### ISSUE TITLE
能否给个详细的用法

### ISSUE THREAD

**Issue by allanGoldZhiKang** [flexih/Snake#2]
bin/snake -l demo/release/demo-LinkMap-normal-x86_64.txt demo/release/demo.app/demo -c
Segmentation fault: 11

**Comment by flexih** [comment]
可以看下介绍文章，[Objective-C二进制瘦身](https://www.jianshu.com/p/e3cf048c67aa)。

**Comment by flexih** [comment]
另外，这个例子可以执行了，增加了缺少的demo.app。
