### ISSUE TITLE
得到输出结果或者返回值

### ISSUE THREAD

**Issue by iPermanent** [flexih/Snake#5]
目前只做到了在控制台输出，是否可以做成支持回输出文件参数保存本地文件，或者直接给出一个返回值呢，这样自动化脚本分析的时候，可以做流程化了

**Comment by flexih** [comment]
是可以输出到文件的：
-j, --json Output json format

**Comment by iPermanent** [comment]
> 是可以输出到文件的：
> -j, --json Output json format

这个只是按json格式控制台输出不是输出文件路径吧

**Comment by Auk513** [comment]
> > 是可以输出到文件的：
> > -j, --json Output json format
> 
> 这个只是按json格式控制台输出不是输出文件路径吧

snake -l [link-map-path] [binary-path] -c -j > [output-path]
